"""create trustlens tables

Revision ID: 0d024f7c87ea
Revises: 
Create Date: 2026-07-05 10:04:35.217373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d024f7c87ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table('questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('original_question', sa.Text(), nullable=False),
    sa.Column('refined_question', sa.Text(), nullable=True),
    sa.Column('selected_question', sa.Text(), nullable=False),
    sa.Column('answer_purpose', sa.String(length=40), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=True),
    sa.Column('verification_basis', sa.String(length=40), nullable=True),
    sa.Column('suggested_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('current_stage', sa.String(length=60), server_default='question_analysis', nullable=False),
    sa.Column('display_stage', sa.String(length=60), server_default='question_analysis', nullable=False),
    sa.Column('progress_percent', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('stage_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('estimated_remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('execution_mode', sa.String(length=20), server_default='mock', nullable=False),
    sa.Column('reanalysis_of_question_id', sa.UUID(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("answer_purpose IN ('fact_check','concept_understanding','decision_support','evidence_focused','risk_analysis')", name='ck_questions_answer_purpose'),
    sa.CheckConstraint("execution_mode IN ('mock','real')", name='ck_questions_execution_mode'),
    sa.CheckConstraint("status IN ('queued','processing','completed','failed')", name='ck_questions_status'),
    sa.CheckConstraint('progress_percent BETWEEN 0 AND 100', name='ck_questions_progress'),
    sa.ForeignKeyConstraint(['reanalysis_of_question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_answer_purpose', 'questions', ['answer_purpose'], unique=False)
    op.create_index('idx_questions_created_at', 'questions', ['created_at'], unique=False)
    op.create_index('idx_questions_question_type', 'questions', ['question_type'], unique=False)
    op.create_index('idx_questions_reanalysis', 'questions', ['reanalysis_of_question_id'], unique=False)
    op.create_index('idx_questions_status', 'questions', ['status'], unique=False)
    op.create_index('idx_questions_tags_gin', 'questions', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_questions_verification_basis', 'questions', ['verification_basis'], unique=False)
    op.create_table('ai_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('model_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('model_grade', sa.String(length=50), nullable=True),
    sa.Column('model_score_reason', sa.Text(), nullable=True),
    sa.Column('model_score_detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("provider IN ('gpt','claude','gemini')", name='ck_ai_responses_provider'),
    sa.CheckConstraint("status IN ('pending','success','failed','timeout')", name='ck_ai_responses_status'),
    sa.CheckConstraint('model_score IS NULL OR model_score BETWEEN 0 AND 100', name='ck_ai_responses_model_score'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'provider', name='uq_ai_responses_question_provider')
    )
    op.create_index('idx_ai_responses_model_score', 'ai_responses', ['model_score'], unique=False)
    op.create_index('idx_ai_responses_provider_status', 'ai_responses', ['provider', 'status'], unique=False)
    op.create_index('idx_ai_responses_question', 'ai_responses', ['question_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.String(length=20), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('normalized_claim', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('verification_basis', sa.String(length=40), nullable=False),
    sa.Column('source_models', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('consensus_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('consensus_level', sa.String(length=20), nullable=True),
    sa.Column('verification_status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('verification_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verification_reason', sa.Text(), nullable=True),
    sa.Column('verification_mode', sa.String(length=30), nullable=True),
    sa.Column('direct_evidence_strength', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cross_source_agreement', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('positive_factors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('deductions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("importance IN ('core','supporting')", name='ck_claims_importance'),
    sa.CheckConstraint("verification_status IN ('pending','verified','weak_evidence','unsupported','contradicted')", name='ck_claims_verification_status'),
    sa.CheckConstraint('consensus_score IS NULL OR consensus_score BETWEEN 0 AND 100', name='ck_claims_consensus_score'),
    sa.CheckConstraint('cross_source_agreement IS NULL OR cross_source_agreement BETWEEN 0 AND 100', name='ck_claims_cross_source_agreement'),
    sa.CheckConstraint('direct_evidence_strength IS NULL OR direct_evidence_strength BETWEEN 0 AND 100', name='ck_claims_direct_evidence_strength'),
    sa.CheckConstraint('verification_confidence IS NULL OR verification_confidence BETWEEN 0 AND 100', name='ck_claims_verification_confidence'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'display_id', name='uq_claims_question_display_id')
    )
    op.create_index('idx_claims_importance', 'claims', ['question_id', 'importance'], unique=False)
    op.create_index('idx_claims_question', 'claims', ['question_id'], unique=False)
    op.create_index('idx_claims_source_models_gin', 'claims', ['source_models'], unique=False, postgresql_using='gin')
    op.create_index('idx_claims_verification_basis', 'claims', ['question_id', 'verification_basis'], unique=False)
    op.create_index('idx_claims_verification_status', 'claims', ['question_id', 'verification_status'], unique=False)
    op.create_table('final_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=False),
    sa.Column('cautions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('key_issues', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cross_review', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('claim_distribution', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('claim_evidence_relations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('final_answer_mode', sa.String(length=40), nullable=False),
    sa.Column('cross_review_mode', sa.String(length=40), nullable=False),
    sa.Column('judge_provider', sa.String(length=50), nullable=True),
    sa.Column('judge_model', sa.String(length=150), nullable=True),
    sa.Column('judge_attempts', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('fallback_reason', sa.Text(), nullable=True),
    sa.Column('result_version', sa.String(length=20), server_default='1.1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('judge_attempts >= 0', name='ck_final_results_judge_attempts'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('search_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=40), server_default='unknown', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("source_type IN ('official','government','academic','paper','documentation','news','blog','community','unknown')", name='ck_search_documents_source_type'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'url', name='uq_search_documents_question_url')
    )
    op.create_index('idx_search_documents_content_hash', 'search_documents', ['content_hash'], unique=False)
    op.create_index('idx_search_documents_published_at', 'search_documents', ['published_at'], unique=False)
    op.create_index('idx_search_documents_question', 'search_documents', ['question_id'], unique=False)
    op.create_index('idx_search_documents_source_type', 'search_documents', ['source_type'], unique=False)
    op.create_table('trust_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('evidence_support_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source_quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('consensus_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('logic_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('freshness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('base_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('contradiction_penalty', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('risk_penalty', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('score_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('deductions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('calculation_detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('formula_version', sa.String(length=20), server_default='1.1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('contradiction_penalty >= 0 AND risk_penalty >= 0', name='ck_trust_scores_penalties'),
    sa.CheckConstraint('evidence_support_score BETWEEN 0 AND 100 AND source_quality_score BETWEEN 0 AND 100 AND consensus_score BETWEEN 0 AND 100 AND logic_score BETWEEN 0 AND 100 AND freshness_score BETWEEN 0 AND 100 AND base_score BETWEEN 0 AND 100 AND total_score BETWEEN 0 AND 100', name='ck_trust_scores_components'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index('idx_trust_scores_total_score', 'trust_scores', ['total_score'], unique=False)
    op.create_table('deterministic_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=40), nullable=False),
    sa.Column('input_expression', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('ai_claimed_result', sa.Text(), nullable=True),
    sa.Column('check_passed', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verification_confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('verification_reason', sa.Text(), nullable=False),
    sa.Column('execution_detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("check_type IN ('calculator','unit_conversion','base_conversion','logic_evaluation','formula','safe_code_execution','rule_based')", name='ck_deterministic_checks_type'),
    sa.CheckConstraint("verification_status IN ('verified','weak_evidence','unsupported','contradicted')", name='ck_deterministic_checks_status'),
    sa.CheckConstraint('verification_confidence BETWEEN 0 AND 100', name='ck_deterministic_confidence'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deterministic_checks_claim', 'deterministic_checks', ['claim_id'], unique=False)
    op.create_index('idx_deterministic_checks_passed', 'deterministic_checks', ['check_passed'], unique=False)
    op.create_index('idx_deterministic_checks_question', 'deterministic_checks', ['question_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', COALESCE(content, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['search_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_hash', name='uq_document_chunks_document_hash'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_index')
    )
    op.create_index('idx_document_chunks_document', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_document_chunks_hash', 'document_chunks', ['chunk_hash'], unique=False)
    op.create_index('idx_document_chunks_search_vector', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('risks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('risk_key', sa.String(length=150), nullable=False),
    sa.Column('risk_type', sa.String(length=40), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affects_core_answer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_by_evidence', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('penalty', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('detected_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('low','medium','high')", name='ck_risks_level'),
    sa.CheckConstraint("risk_type IN ('hallucination','source_credibility','outdated_information','contradiction')", name='ck_risks_type'),
    sa.CheckConstraint('penalty BETWEEN 0 AND 40', name='ck_risks_penalty'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'risk_key', name='uq_risks_question_key')
    )
    op.create_index('idx_risks_claim', 'risks', ['claim_id'], unique=False)
    op.create_index('idx_risks_level', 'risks', ['risk_level'], unique=False)
    op.create_index('idx_risks_question', 'risks', ['question_id'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding_provider', sa.String(length=50), nullable=False),
    sa.Column('embedding_model', sa.String(length=150), nullable=False),
    sa.Column('dimension', sa.Integer(), server_default='1536', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('is_mock', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('dimension = 1536', name='ck_document_embeddings_dimension'),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    op.create_index('idx_document_embeddings_chunk', 'document_embeddings', ['chunk_id'], unique=False)
    op.create_index('idx_document_embeddings_hnsw', 'document_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('evidences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('deterministic_check_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('keyword_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('vector_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('hybrid_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('source_quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('directness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('support_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("relation IN ('support','contradict','neutral')", name='ck_evidences_relation'),
    sa.CheckConstraint('(keyword_score IS NULL OR keyword_score BETWEEN 0 AND 1) AND (vector_score IS NULL OR vector_score BETWEEN 0 AND 1) AND (hybrid_score IS NULL OR hybrid_score BETWEEN 0 AND 1)', name='ck_evidences_search_scores'),
    sa.CheckConstraint('document_id IS NOT NULL OR deterministic_check_id IS NOT NULL', name='ck_evidences_source'),
    sa.CheckConstraint('source_quality_score BETWEEN 0 AND 100 AND directness_score BETWEEN 0 AND 100 AND support_score BETWEEN 0 AND 100', name='ck_evidences_quality_scores'),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deterministic_check_id'], ['deterministic_checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['search_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidences_claim', 'evidences', ['claim_id'], unique=False)
    op.create_index('idx_evidences_hybrid_score', 'evidences', ['claim_id', 'hybrid_score'], unique=False)
    op.create_index('idx_evidences_question', 'evidences', ['question_id'], unique=False)
    op.create_index('idx_evidences_relation', 'evidences', ['claim_id', 'relation'], unique=False)
    op.create_index('idx_evidences_source_type', 'evidences', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_evidences_source_type', table_name='evidences')
    op.drop_index('idx_evidences_relation', table_name='evidences')
    op.drop_index('idx_evidences_question', table_name='evidences')
    op.drop_index('idx_evidences_hybrid_score', table_name='evidences')
    op.drop_index('idx_evidences_claim', table_name='evidences')
    op.drop_table('evidences')
    op.drop_index('idx_document_embeddings_hnsw', table_name='document_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_document_embeddings_chunk', table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index('idx_risks_question', table_name='risks')
    op.drop_index('idx_risks_level', table_name='risks')
    op.drop_index('idx_risks_claim', table_name='risks')
    op.drop_table('risks')
    op.drop_index('idx_document_chunks_search_vector', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('idx_document_chunks_hash', table_name='document_chunks')
    op.drop_index('idx_document_chunks_document', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('idx_deterministic_checks_question', table_name='deterministic_checks')
    op.drop_index('idx_deterministic_checks_passed', table_name='deterministic_checks')
    op.drop_index('idx_deterministic_checks_claim', table_name='deterministic_checks')
    op.drop_table('deterministic_checks')
    op.drop_index('idx_trust_scores_total_score', table_name='trust_scores')
    op.drop_table('trust_scores')
    op.drop_index('idx_search_documents_source_type', table_name='search_documents')
    op.drop_index('idx_search_documents_question', table_name='search_documents')
    op.drop_index('idx_search_documents_published_at', table_name='search_documents')
    op.drop_index('idx_search_documents_content_hash', table_name='search_documents')
    op.drop_table('search_documents')
    op.drop_table('final_results')
    op.drop_index('idx_claims_verification_status', table_name='claims')
    op.drop_index('idx_claims_verification_basis', table_name='claims')
    op.drop_index('idx_claims_source_models_gin', table_name='claims', postgresql_using='gin')
    op.drop_index('idx_claims_question', table_name='claims')
    op.drop_index('idx_claims_importance', table_name='claims')
    op.drop_table('claims')
    op.drop_index('idx_ai_responses_question', table_name='ai_responses')
    op.drop_index('idx_ai_responses_provider_status', table_name='ai_responses')
    op.drop_index('idx_ai_responses_model_score', table_name='ai_responses')
    op.drop_table('ai_responses')
    op.drop_index('idx_questions_verification_basis', table_name='questions')
    op.drop_index('idx_questions_tags_gin', table_name='questions', postgresql_using='gin')
    op.drop_index('idx_questions_status', table_name='questions')
    op.drop_index('idx_questions_reanalysis', table_name='questions')
    op.drop_index('idx_questions_question_type', table_name='questions')
    op.drop_index('idx_questions_created_at', table_name='questions')
    op.drop_index('idx_questions_answer_purpose', table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
